### ISSUE TITLE
Codeforces solution to 1860 Game on Permutation of 1400 rating and others

### ISSUE THREAD

**Issue by Nikhil-IITG** [dixitt5/CP-Solutions#276]
Hello sir/ma'am, please create this issue and assign it to me so I can post my solutions and contribute to your CF solutions repository. Thank you

**Comment by dixitt5** [comment]
assigned the issue to you @Nikhil-IITG !

**Comment by Nikhil-IITG** [comment]
Pulled request for 2 solutions. Would be contributing to the repository further as well, thank you for assigning.

**Comment by dixitt5** [comment]
I have merged both of the PRs, feel free to star the repo, so more people can contribute!
