### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by Manul28** [dixitt5/CP-Solutions#299]
@dixitt5 Can you assign me this with hacktoberfest accepted label so that I can make a PR?

I have already made a PR can you please accept that?

**Comment by Shivansh230367** [comment]
Hey @dixitt5 , I am interested in contributing to this issue.
So, please assign me for this.

**Comment by dixitt5** [comment]
@Shivansh230367 I'll be assigning this issue to @Manul28 as per the chronological order, sure you can create new one so I can assign it to you.

**Comment by Manul28** [comment]
thank you
