### ISSUE TITLE
Adding Essential Java Programs

### ISSUE THREAD

**Issue by Divyanshi014** [dixitt5/CP-Solutions#333]
I want to add Tower of Hanoi, Merge Sort, and Quick Sort Java Programs

**Comment by dixitt5** [comment]
@Divyanshi014 issue is assigned to you!

**Comment by AdarshInDev** [comment]
I want to add  Tree Traversal Techniques in  JAVA( preorder , inorder, postorder) @dixitt5

**Comment by AdarshInDev** [comment]
pls assign it to me @dixitt5 admin

**Comment by Divyanshi014** [comment]
> @Divyanshi014 issue is assigned to you!

Sure!

**Comment by dixitt5** [comment]
@AdarshInDev hey Adarsh, you can create a new issue for the same!

**Comment by AdarshInDev** [comment]
> @AdarshInDev hey Adarsh, you can create a new issue for the same!
done  @dixitt5
