### ISSUE TITLE
Add Tree Traversal Techniques in Java (Preorder , Inorder , Postorder)

### ISSUE THREAD

**Issue by AdarshInDev** [dixitt5/CP-Solutions#338]
to add postorder  ,  inorder ,  preorder traversal techniques in JAVA

**Comment by manthankhawse** [comment]
hello @AdarshInDev I would like to work on this issue can you please assign it to me? Thanks.

**Comment by dixitt5** [comment]
@AdarshInDev issue is assigned to you !
