### ISSUE TITLE
Add BFS Algorithm In C++ 

### ISSUE THREAD

**Issue by AdarshInDev** [dixitt5/CP-Solutions#355]
pls assign this to me @dixitt5

**Comment by AdarshInDev** [comment]
Please tell me How can I complete my 3 more pull request left  in Hacktober. That will be kind of you @dixitt5

**Comment by dixitt5** [comment]
Hey @AdarshInDev, Hope you're okay, this is certainly a good start for your open-source journey, but I would suggest exploring more of the repositories that have many good first issues, that you can try. you can start by searching "good first issue" on GitHub or Google to find issues that you can solve and contribute.

**Comment by AdarshInDev** [comment]
thanks @dixitt5  for your words I will Surely follow

**Comment by abhi-yo** [comment]
@dixitt5 can I contribute please?

**Comment by dixitt5** [comment]
@abhi-yo sure you can, create a new issue on the repo for the same!
